version: '3'
services:

 mysql:
   image: mysql:8.0
   volumes:
     - db_data:/var/lib/mysql
   environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_PASSWORD: root
    MYSQL_DATABASE: rsvp
   networks:
    - rsvpnet

 web:
   build: . 
   ports:
    - "5000:5000"
   environment:
    TEXT1: Hackfest 
    TEXT2: Registration 
    ORGANIZER: UVCE
    MYSQL_HOST: mysql
    MYSQL_DB: rsvp
   networks:
    - rsvpnet

networks:
  rsvpnet:

volumes:
   db_data:
